sprites = {}

sprites.bullet = love.graphics.newImage('resource/image/laser1.png')
sprites.player = love.graphics.newImage('resource/image/player_sprite.png')
sprites.enemy1 = love.graphics.newImage('resource/image/enemy1.png')
sprites.enemy2 = love.graphics.newImage('resource/image/enemy2.png')
sprites.enemy3 = love.graphics.newImage('resource/image/enemy3.png')
sprites.enemy4 = love.graphics.newImage('resource/image/enemy4.png')
sprites.enemy_bullet = love.graphics.newImage('resource/image/enemy_laser.png')
sprites.enemy_boss = love.graphics.newImage('resource/image/enemy_boss.png')
sprites.orbit_enemy = love.graphics.newImage('resource/image/orbit_enemy.png')
sprites.star = love.graphics.newImage('resource/image/star.png')
sprites.menu_arrow1 = love.graphics.newImage('resource/image/menu_arrow1.png')
sprites.menu_arrow2 = love.graphics.newImage('resource/image/menu_arrow2.png')
sprites.blast = love.graphics.newImage('resource/image/blast.png')
sprites.support_char = love.graphics.newImage('resource/image/support_character.png')